### PR TITLE
Proposal, please read

### PR DESCRIPTION
**Pull request by k1r0s**
I really love this mod, but there are couple of things that really hurt when playing along other mods. Other changes are more related to "unfinished" stuff imo.

problem:

1. One may have different mods within a server or modpack and remove vanilla recipes isn't a good idea. What options do we have? through config u can disable `HCCreduceIngots` but then you can't use MF2 Furnaces and Bloomery and vanilla furnace is the way to go. Can't we have both? allow players to enjoy MF2 while others skip its hardcore nature.

Solution: 561bbf8, 6b9bfe8

With these changes; config `HCCRemoveCraft` now comes into play. `HCCreduceIngots` will only toggle if MF2 smelting is available while `HCCRemoveCraft` effectively removes vanilla recipes and, if disabled, will load minecraft vanilla furnace recipes for other ores such as silver, copper, tin..

2. Would like to discuss about wood stats, im open to any change into this. To me t4.silverwood is too easy to find whereas MF2 wood is quite hard, I was unable to find Yew wood yet. IronBark and Ebony are very similar, on the original code seems like ironbark is more suited for construction and, in the other hand, ironbark is better for tool crafting. The problem is how hard to witness Ebony is compared to ironbark.

Solution: 081fb8a

Once again, my changes are result of my own experience with the game. IronBark/Ebony issue may be solved on tweaking config on spawn rates. I find silverwood controversy most relevant.

3. Thread recipe with Vine. Thread is a very needed resource throughout minecraft and yet, even with wool-stick>4thread recipe is hard to mass at the beginning of the game bcoz it depends on seeps (mobs). Everybody knows that many servers cap mob spawning for several reasons and, there may be other problems where players standing nearby dungeons could unintentionally reduce mob spawning on the whole server. Another argument is that tree vines and specially bark is a reliant resource for strong vines since antiquity, hence thread may be produced from it.

Solution: b141750

4. Melee balance is one of my goals and isn't finished yet but here is my point: Heavy weapons are very strong, increased reach is cheaty in my opinion but I agree that should be an option and specially a cheap one. Historically speaking spears and other ranged melee weapons dominate the world for obvious reasons. I found about `useBalance` config and it says that "enable this so heavy weapons usage will be more difficult to spam" but it does nothing. Looking around the code saw that there is a piece of code that is supposed to throw away camera angle when making use of a heavy weapon but somehow was not working.

Solution: 178dc18

ROADMAP: 

- `useBalance` always throws camera angle on the same direction (7pm - 8pm clock wards), I want to make it completely random so u can't effectively spam attacks with a very powerful item.

- MF2 armors make u completely invincible to fire and even LAVA!, would like to deny it. I found the place where armor bonuses are applied but not able to remove fire resistance stuff :\

- Would like to add another layer on the melee mechanics related to weight that player is carring (armour + weapon). Having that attribute a player can miss its attacks on players that wear very less weight compared to them (likely 1/3 of the attacker weight). This is make light armour more appealing.

- Setup a config option to disable other MF2 vanilla overrides, for instance farming mechanincs. 

Overall is hard to see MF2 on any modpacks because is very invasive on vanilla gameplay.

Looking forward for comments. Thanks for the attention :)

### CODE REVIEW

**Comment by k1r0s** [comment]
note: this changes are up and running on my server since 1 month with 48 other mods

**Comment by Sirse** [comment]
Thanks for your contribution!
For now development moved to https://github.com/flyse-ae/MineFantasyII-Cont fork.
You can check new code and create new pullrequest with your changes to @flyse-ae fork. 

Flyse's fork will been merged into main repo in the future (it semi-stable for now, also, main MF code has a few critical network vulnerabilities).

**Comment by k1r0s** [comment]
If this repo is dead then u should make a reference somewhere, please do :)

**Comment by k1r0s** [comment]
Im wondering who has rights on curse in order ro push updates

**Comment by ghost** [comment]
Is this mod going on Mc 1.12.2+ and 1.14+ ?

**Pull request merged**
